name: Verify Dockerfile build valid

on:
  push:
    branches:
      - '!master'
      - '**'

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Test Build
        run: |
          for file in $(ls *.Dockerfile); do
            docker buildx build --platform linux/amd64 -f $file --output type=local,dest=. .
          done