name: Verify Dockerfile build valid

on:
  push:
    branches:
      - '!master'
      - '**'

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.get-files.outputs.matrix }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get files
        id: get-files
        run: |
          echo "matrix=$(ls *.Dockerfile | tr -d '\n' | jq -R -s -c 'split(" ")')" >> $GITHUB_OUTPUT
      - name: Verify Output
        run: echo '${{ steps.get-files.outputs.matrix }}'
  verify:
    runs-on: ubuntu-latest
    needs: [ prepare ]
    strategy:
      fail-fast: true
      matrix:
        file: ${{ fromJson(needs.prepare.outputs.matrix) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Test Build
        run: docker buildx build --platform linux/amd64 -f ${{ matrix.file }} .